### ISSUE TITLE
How to expose more than 1 port to other instances?

### ISSUE THREAD

**Issue by skyrimforest** [oakestra/oakestra#294]
## Short
It is not declared how to expose more than 1 port to other instances,  I want to deploy a rabbitmq in oakestra, and I want to expose 5672 and 15672. Can you explain how to build my service descriptor? Thank you!

## Development time
The expected time required to complete the development of this proposal 

## Status
help wanted 

## Checklist
 
- [ ] Discussed
- [ ] Documented
- [ ] Implemented
- [ ] Tested

**Comment by giobart** [comment]
Hello @skyrimforest  , to other service instances you don't need to manually expose ports. The `port` field of the deployment descriptor is only to expose ports to public node IP. Service-to-service overlay network via service IP automatically enters the target service network namespace. The port exposure, therefore, is only needed to access a service from a host (client) outside Oakestra. 

### Example:

service A (service IP 10.30.0.1, node IP 130.40.30.12) and must be reachable by external clients at port 5000 and 6000 and exposes port 50500 for service B
service B (service IP 10.30.0.2) contacts service A at port 50500 and exposes 43444 for service C
service C (service IP 10.30.0.3) contacts service B at port 43444

In the deployment descriptor:

service A: `"port":"5000:5000/tcp,6000:6000/tcp"`
service B: `"port":""`
service C: `"port":""`

if service B performs a request http://10.30.0.1:50500 it works ✅
if service C performs a request http://10.30.0.2:43444 it works ✅
if service B performs a request http://130.40.30.12:6000 it works ✅
if service B performs a request http://130.40.30.12:50500 it does not work ❌ 
(because port A:50500 is not exposed to the public IP but available only via "local" network [Service IP])
